language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
sudo: required
before_script:
  - sudo npm install -g bower
  - sudo npm install phantomjs
  - sudo npm install -g karma
  - find /home/travis/.nvm/v0.10.44/bin/node -type d -exec chmod 755 {} \;
  - find /home/travis/.nvm/v0.10.44/bin/node -type f -exec chmod 644 {} \; 
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - bower install
  - grunt build
